---
language: ruby
bundler_args: "--without system"
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
jdk:
  - openjdk11
before_install: gem install bundler -v '< 2' --no-document
matrix:
  include:
    - stage: r10k tests
      rvm: 2.7.0
    - stage: r10k tests
      rvm: 2.6.5
    - stage: r10k tests
      rvm: 2.5.0
    - stage: r10k tests
      rvm: 2.4.0
    - stage: r10k tests
      rvm: 2.3.0
    - stage: r10k tests
      rvm: jruby
    - stage: r10k container tests
      dist: focal
      language: ruby
      services:
        - docker
      rvm: 2.6.6
      env:
        # necessary to prevent overwhelming TravisCI build output limits
        - DOCKER_BUILD_FLAGS="--progress plain"
      script:
        - set -e
        - cd docker
        - make lint
        - make build
        - make test
